language: python
python:
  - "3.4"      # current default Python on Travis CI
  
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - SECRET_KEY="whatever" manage.py test